workflows:
  rideshare:
    instance_type:mac_pro
    max_build_duration:100
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials

      vars:
        GOOGLE_PLAY_TRACK:'beta'
      flutter:stable
      xcode:stable
      
    scripts:
        - name: Set up local.properties
          script: | 
            echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
        - name: Get Flutter packages
          script: | 
            flutter packages pub get
        - name: Build apk with Flutter
          script: | 
            flutter build apk --release

        artifacts:
          - build/**/outputs/**/*.apk
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log